import type { NextPage } from 'next'
import Head from 'next/head'
import Menu from '../components/menu'

const Home: NextPage = () => {
  return (
    <div className="bg-black h-screen">
      <Head>
        <title>Shopping Online</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Menu/>
      </main>
    </div>
  )
}

export default Home
